## **NumPy学习笔记3**⭐

In [1]:
import numpy as  np

### ***numpy.matrix***
`class numpy.matrix(data, dtype=None, copy=True)`

从类似数组的对象或数据字符串返回矩阵。  
矩阵是一种特殊的二维阵列，通过运算保持其二维特性。  
它有一些特殊的运算符，如*（矩阵乘法）和**（矩阵幂）。

- Parameters:
  - data: array_like or string  
    如果数据是字符串，则它被解释为一个矩阵，用逗号或空格分隔列，用分号分隔行。
  - dtype: data-type  
    输出矩阵的数据类型。
  - copy: bool  
    如果数据已经是ndarray，则此标志确定是否复制数据（默认值 True），或是否构造视图。

In [3]:
# string
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [4]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

### ***numpy.mat***  
`numpy.mat(data, dtype=None)`

将输入解释为矩阵。  
Unlike `matrix` does not make a copy if the input is already a matrix or an ndarray.  
Equivalent to `matrix(data, copy=False)`.

- Parameters:
  - data: array_like  
    输入数据。
  - dtype: data-type  
    输出矩阵的数据类型。

In [7]:
x=np.array([[1,2],[3,4]])
m=np.mat(x)
x[0,0]=5
m

matrix([[5, 2],
        [3, 4]])

In [10]:
x=np.array([[1,2],[3,4]])
m=np.matrix(x)
x[0,0]=5
m

matrix([[1, 2],
        [3, 4]])

### ***numpy.ones***
`numpy.ones(shape, dtype=None, order='C', *, like=None)`

返回一个给定形状和类型的新数组，并填充1。
### ***numpy.zeros***
`numpy.zeros(shape, dtype=float, order='C', *, like=None)`

返回一个给定形状和类型的新数组，并填充0。
- Parameters:
  - shape: int or sequence of ints  
    新数组形状。
  - dtype: data-type, optional  
    数组所需的数据类型（默认 `numpy.float64`）。
  - order: {‘C’, ‘F’}, optional, default: C  
    是按行主（C样式）还是列主（Fortran样式）顺序在内存中存储多维数据。
  - like: array_like, optional  
    引用对象以允许创建不是NumPy数组的数组。  
    如果像这样传入的数组支持__array_function__协议，则结果将由其定义。  
    在这种情况下，它确保创建与通过此参数传入的数组对象兼容的数组对象。

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [14]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [16]:
arr=np.array([[1,2],[2,3],[3,4]])
np.ones(arr.shape)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])