## **NumPy学习笔记2**⭐

In [2]:
import numpy as  np

#### tile函数

- 用法：`np.tile(A,res)`

- 作用：tile这个函数把数组 A 当成一个元素来构造 shape 为 res 的数组

- 参数说明：
  - A 是个数组
  - reps 是个元组 

In [3]:
a = np.array([0,1,2,3])
np.tile(a, 2)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [4]:
a = np.array([0,1,2,3])
np.tile(a, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [5]:
a = np.array([0,1,2,3])
np.tile(a, (2,1,2))

array([[[0, 1, 2, 3, 0, 1, 2, 3]],

       [[0, 1, 2, 3, 0, 1, 2, 3]]])

In [10]:
dataSet = np.array([[1,101],[5,89],[108,5],[115,8]])
dataSetSize = dataSet.shape[0]
diffMat = np.tile([101,20], (dataSetSize, 1))
print(diffMat)

[[101  20]
 [101  20]
 [101  20]
 [101  20]]
