## **NumPy学习笔记2**⭐

In [2]:
import numpy as  np

#### tile函数

- 用法：`np.tile(A,res)`

- 作用：tile这个函数把数组 A 当成一个元素来构造 shape 为 res 的数组

- 参数说明：
  - A 是个数组
  - reps 是个元组 

In [3]:
a = np.array([0,1,2,3])
np.tile(a, 2)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [4]:
a = np.array([0,1,2,3])
np.tile(a, (2,2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [5]:
a = np.array([0,1,2,3])
np.tile(a, (2,1,2))

array([[[0, 1, 2, 3, 0, 1, 2, 3]],

       [[0, 1, 2, 3, 0, 1, 2, 3]]])

In [10]:
dataSet = np.array([[1,101],[5,89],[108,5],[115,8]])
dataSetSize = dataSet.shape[0]
diffMat = np.tile([101,20], (dataSetSize, 1))
print(diffMat)

[[101  20]
 [101  20]
 [101  20]
 [101  20]]


#### argsort函数

- 用法：`np.argsort(a, axis=-1, kind='quicksort', order=None)`

- 作用：将 a 中的元素从小到大排列 (升序)，提取其在排列前对应的 index (索引) 输出

- 参数说明：
  - a 是个数组
  - axis 默认为-1
  - kind 默认为'quicksort'快排
  - order 如果数组包含字段，则是要排序的字段

In [11]:
# 一维数组
x=np.array([1,4,3,-1,6,9])
y=np.argsort(x)
print('一维数组的排序结果：{}'.format(y))

一维数组的排序结果：[3 0 2 1 4 5]


In [14]:
# 二维数组
x = np.array([[1,5,4],[-1,6,9]])
# 沿着行向下(每列)的元素进行排序
print(np.argsort(x,axis=0))
# 沿着列向右(每行)的元素进行排序
print(np.argsort(x,axis=1))

[[1 0 0]
 [0 1 1]]
[[0 2 1]
 [0 1 2]]
