## **NumPy学习笔记3**⭐

In [1]:
import numpy as  np

### **numpy.matrix**

`class numpy.matrix(data, dtype=None, copy=True)`

从类似数组的对象或数据字符串返回矩阵。  
矩阵是一种特殊的二维阵列，通过运算保持其二维特性。  
它有一些特殊的运算符，如*（矩阵乘法）和**（矩阵幂）。

- Parameters:
  - data: array_like or string  
    如果数据是字符串，则它被解释为一个矩阵，用逗号或空格分隔列，用分号分隔行。
  - dtype: data-type  
    输出矩阵的数据类型。
  - copy: bool  
    如果数据已经是ndarray，则此标志确定是否复制数据（默认值 True），或是否构造视图。

In [3]:
# string
a = np.matrix('1 2; 3 4')
a

matrix([[1, 2],
        [3, 4]])

In [4]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

### **numpy.mat**

`numpy.mat(data, dtype=None)`

将输入解释为矩阵。  
Unlike `matrix` does not make a copy if the input is already a matrix or an ndarray.  
Equivalent to `matrix(data, copy=False)`.

- Parameters:
  - data: array_like  
    输入数据。
  - dtype: data-type  
    输出矩阵的数据类型。

In [7]:
x=np.array([[1,2],[3,4]])
m=np.mat(x)
x[0,0]=5
m

matrix([[5, 2],
        [3, 4]])

In [10]:
x=np.array([[1,2],[3,4]])
m=np.matrix(x)
x[0,0]=5
m

matrix([[1, 2],
        [3, 4]])

### **numpy.ones**

`numpy.ones(shape, dtype=None, order='C', *, like=None)`

返回一个给定形状和类型的新数组，并填充1。
### **numpy.zeros**

`numpy.zeros(shape, dtype=float, order='C', *, like=None)`

返回一个给定形状和类型的新数组，并填充0。
- Parameters:
  - shape: int or sequence of ints  
    新数组形状。
  - dtype: data-type, optional  
    数组所需的数据类型（默认 `numpy.float64`）。
  - order: {‘C’, ‘F’}, optional, default: C  
    是按行主（C样式）还是列主（Fortran样式）顺序在内存中存储多维数据。
  - like: array_like, optional  
    引用对象以允许创建不是NumPy数组的数组。  
    如果像这样传入的数组支持__array_function__协议，则结果将由其定义。  
    在这种情况下，它确保创建与通过此参数传入的数组对象兼容的数组对象。

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [14]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [16]:
arr=np.array([[1,2],[2,3],[3,4]])
np.ones(arr.shape)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### **numpy.multiply**

`numpy.multiply(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'multiply'>`

按元素相乘参数。

- Parameters:
  - x1, x2:array_like  
    要相乘的输入数组。  
    如果x1.shape！=x2.shape，它们必须可以广播到公共形状（这将成为输出的形状）。
  - out:ndarray, None, or tuple of ndarray and None, optional  
    存储结果的位置。  
    如果提供，它必须具有输入广播到的形状。  
    如果未提供或无，则返回新分配的数组。  
    元组（只能作为关键字参数）的长度必须等于输出数。
  - where:array_like, optional  
    此条件通过输入广播。  
    在条件为True的位置，输出数组将设置为ufunc结果。在其他地方，out数组将保留其原始值。  
    请注意，如果通过默认out=None创建未初始化的输出数组，则其中条件为False的位置将保持未初始化状态。

In [21]:
# 标量相乘
np.multiply(2.0, 4.0)

8.0

In [23]:
x1 = np.arange(9.0).reshape((3, 3))
print(x1)
x2 = np.arange(3.0)
print(x2)
np.multiply(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [24]:
# * 等价 np.multiply
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1 * x2

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [26]:
x1=np.array([1,2,3])
print(x1)
x2=np.array([[1],[2],[3]])
print(x2)
x1*x2

[1 2 3]
[[1]
 [2]
 [3]]


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### **numpy.multiply**

`numpy.sign(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'sign'>`

返回数字符号的逐元素指示。  
The sign function returns `-1 if x < 0, 0 if x==0, 1 if x > 0`. nan is returned for nan inputs.  
For complex (复数) inputs, the sign function returns `sign(x.real) + 0j if x.real != 0 else sign(x.imag) + 0j`.  
complex(nan, 0) is returned for complex nan inputs.



- Parameters:
  - x:array_like  
    输入值。
  - out：ndarray, None, or tuple of ndarray and None, optional
  - where:array_like, optional 

In [27]:
np.sign([-5., 4.5])

array([-1.,  1.])

In [28]:
np.sign(0)

0

In [29]:
np.sign(5-2j)

(1+0j)