## **NumPy学习笔记1**⭐

1. 多维数组的创建，*array*函数，*arange*函数，数据类型转换。

2. 多维数组的索引和切片，间隔选取，翻转。

3. 改变数组的维度，分别介绍了*ravel*函数、*flatten*函数、*reshape*函数、*resize*函数、*transpose*函数的用法。

In [1]:
import numpy as np

### <1.多维数组的创建>

#### Array函数

- 用法: `np.array(object, dtype=None, copy=True, order=‘K’, subok=False, ndmin=0)`

- 作用: 创建一个数组

- 参数说明:
  - object:数组本身；
  - dtype :数据类型；
  - order :{‘K’,‘A’,‘C’,‘F’},默认顺序为“K”；
  - ndmin :指定结果数组应具有的最小维数。

In [2]:
# 一维数组创建
a=np.array([1,2,3])
# 二维数组创建
b=np.array([[1,2,1],[2,3,2]])

a,b

(array([1, 2, 3]),
 array([[1, 2, 1],
        [2, 3, 2]]))

In [3]:
print(a.shape)
print(b.shape)
# 二维数组b，b.shape[0]代表行数，b.shape[1]代表列数
print(b.shape[0])
print(b.shape[1])

(3,)
(2, 3)
2
3


In [4]:
'''
ndarray是一个多维数组对象，该对象由实际的数据、描述这些数据的元数据组成，
大部分数组操作仅仅修改元数据部分，而不改变底层的实际数据。
'''
type(a)

numpy.ndarray

#### Arange函数

- 用法：np.arange()函数分为一个参数，两个参数，三个参数三种情况

- 作用: 返回一个有终点和起点的固定步长的排列

In [5]:
# 创建数组
s1=np.arange(5)
s2=np.arange(1,5)
s3=np.arange(1,5,2)

In [6]:
s1,s2,s3

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4]), array([1, 3]))

In [7]:
'''
数组的shape属性返回一个元祖(tuple)，
元组中的元素即NumPy数组每一个维度的大小。
'''
print(s1.shape)
print(type(s1.shape))

(5,)
<class 'tuple'>


In [8]:
# array元素类型
s1.dtype

dtype('int32')

In [9]:
# 元素选取[]
a =np.array([[1,2],[3,4]])
print (a[0,0])
print (a[0,1])

1
2


#### 数据类型转换

- Numpy除了Python支持的整型、浮点型、复数型之外，还有很多其他的数据类型。

- 每一种数据类型均有对应的类型转换函数,复数不能转换成整数和浮点数。

In [10]:
print (np.float64(42))
print (np.int8(42.0))
# print (np.bool(42))
# print (np.float(True))

42.0
42


In [11]:
# Numpy数组中每一个元素均为相同的数据类型，现在给出单个元素所占字节
a.dtype

dtype('int32')

In [12]:
a.dtype.itemsize

4

### <2.数组的索引和切片>

In [13]:
a=np.arange(9)
# 下标0-7，步长2
print(a[:7:2])
# 翻转
print(a[::-1])

[0 2 4 6]
[8 7 6 5 4 3 2 1 0]


In [14]:
# 创建三维数组,利用reshape函数(2,3,4)
# 类比楼层房间，即层、行、列
b =np.arange(24).reshape(2,3,4)
print (b.shape)
print (b)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [15]:
# 选取第一层所有房间
print (b[0])
print (b[0,:,:])
print (b[0,...])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
# 间隔选取[::,::,::,...]
print (b[0,::2,::2])
# 所有维度翻转
print (b[::-1,::-1,::-1])

[[ 0  2]
 [ 8 10]]
[[[23 22 21 20]
  [19 18 17 16]
  [15 14 13 12]]

 [[11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]


### <3.改变数组维度>

In [17]:
# ravel 展平
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
# flatten 展平
'''
flatten函数会请求分配内存来保存结果，
而ravel函数只是返回数组的一个视图（view）
'''
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
# reshape 不改变源操作数组
print (b.reshape(4,6))
print (b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
# resize 改变源操作数组
b.resize(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
# transpose 转置矩阵
b.transpose()

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])