## **NumPy学习笔记1**⭐
Pandas含有使数据分析工作变得更快更简单的高级数据结构和操作工具。  
Pandas基于NumPy构建，让以NumPy为中心的应用变得更加简单。

1. Pandas数据结构
   
2. 索引对象

In [16]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### <1.Pandas数据结构>
Pandas的两个主要数据结构是：Series和DataFrame。

#### 🧩Serise
Series是一种类似于一维数组的对象，  
它由一组数据（各种NumPy数据类型）以及一组与之相关的数据索引组成。

##### 1.Serise的构建

In [17]:
# Series的字符串表现形式为：索引在左边，值在右边。
# 由于我们没有为数据指定索引，于是会自动创建一个0到N-1的整数索引
obj1=Series([1,2,3,4])
obj1

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
# 获取Series的values和index属性
print(obj1.values)
print(obj1.index)

[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)


In [19]:
# 创建Series带有可以对各个数据点进行标记的索引
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [20]:
print(obj2.values)
print(obj2.index)

[ 4  7 -5  3]
Index(['d', 'b', 'a', 'c'], dtype='object')


##### 2.通过Python字典创建Serise

In [21]:
# 传入Python字典，原字典的键成为Series的索引
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
# sdata中跟states索引项匹配的值会被找出来并放到相应的位置上
sindex = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=sindex)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
# 判断是否为空
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
# Series自动对齐
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

##### 3.Series的name属性

In [25]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

##### 4.修改Series的索引

In [26]:
obj1.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj1

Bob      1
Steve    2
Jeff     3
Ryan     4
dtype: int64

#### 🧩DataFrame
DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型。  
DataFrame既有行索引也有列索引，它可以被看做由Series组成的字典(共用同一个索引)。

##### 1.DataFrame的构建
最常用是直接传入一个由等长列表或NumPy数组组成的字典。

In [27]:
# DataFrame会自动加上索引，且全部被有序排列
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame1 = DataFrame(data)
frame1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
# 如果指定列序列，则DataFrame的列就会按照指定顺序进行排列
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [29]:
# 如果传入的列在数据中找不到，就会产生NA值
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
         index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

##### 2.DataFrame的行列操作
通过类似字典标记的方式或属性的方式，可以将DataFrame的列获取为一个Series。

In [30]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [31]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [38]:
# 第一行数据
frame2.iloc[0]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [41]:
# 修改咧
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [42]:
# 将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。
# 如果赋值的是一个Series，就会精确匹配DataFrame的索引。
frame2['debt'] = [1, 2, 3, 4, 5]
frame2

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5

In [43]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [44]:
# 为不存在的列赋值会创建出一个新列
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [45]:
# 删除咧
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

##### 3.DataFrame嵌套字典
如果数据形式是嵌套字典（字典的字典），将它传给DataFrame，它会被解释为：  
外层的键作为列，内层的键则作为行索引。

In [46]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [47]:
# 对结果进行转置
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

🔔可以输入给DataFrame构造器的数据：

- 二维ndarray： 数据矩阵
- 由数组、列表或元组组成的字典： 每个序列会变成DataFrame的一列。所有序列的长度必须相同
- NumPy的结构化/记录数组： 类似于 有数组组成的字典
- 由Series组成的字典
- 由字典组成的字典
- 字典或Series的列表
- 由列表或元组组成的列表
- 另一个DataFrame
- NumPy的MaskedArray

##### 4.DataFrame的属性

In [48]:
# 设置DataFrame的index和columns的name属性，并显示出来
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [49]:
# DataFrame的values属性会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### <2.索引对象>
pandas的索引对象负责轴标签和其他元数据(比如轴名称等)。  
构建Series或DataFrame时， 所用到的任何数组或其他序列的标签都会被转换成一个Index。

In [50]:
obj = Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [51]:
index[1:]

Index(['b', 'c'], dtype='object')